#!/bin/bash
set -e  # exit on failure
set -u  # treat unset variables as an error

# args
ADDRESS="$1"
LANGUAGE="$2"


# get script path without realpath
pushd "$(dirname "$0")" > /dev/null
SCRIPT_PATH=$(pwd -P)
popd > /dev/null

# Send welcome message to user
MESSAGE_FILE="$SCRIPT_PATH/../message_templates/${LANGUAGE}/welcome_message.txt"
/opt/kulloshooter/kullo-shooter --to "$ADDRESS" --messageFile "$MESSAGE_FILE"

# Send notification email to admin
echo "Address: $ADDRESS" | mail -s "New Kullo User" buero@kullo.net
